openapi: 3.0.0
info:
  title: data types for NSSO employer identifiers
  version: ${project.version}-beta
servers: []
paths: {}
components:
  schemas:
    EmployerId:
      description: Definitive or provisional NSSO number, assigned to each registered employer or local or provincial administration.
      type: integer
      minimum: 197
      maximum: 5999999999 
      # Provisional NSSO numbers start with 5, definitive numbers are maximum 9 digits long
      # also see entries nssoNumber, pplNumber and provisionalNssoNumber in https://github.com/belgif/fedvoc/blob/master/FederalServicePlatform-Vocabularies.xlsx for the definitions and formats of the subtypes of employer identifiers