openapi: 3.0.0
info:
  title: data types for NSSO employer identifiers
  version: ${project.version}-beta
servers: []
paths: {}
components:
  schemas:
    EmployerId:
      description: Definitive or provisional NSSO number, assigned to each registered employer or local or provincial administration.
      type: string
      pattern: '^5?\d{9}$'
      example: '000100006'