swagger: "2.0"
info:
  title: data types for NSSO employer identifiers
  version: ${project.version}-beta
paths: {}
definitions:
  EmployerId:
    description: Definitive or provisional NSSO number, assigned to each registered employer or local or provincial administration.
    type: integer
    minimum: 0
    maximum: 5999999999 # Provisional NSSO numbers start with 5, definitive numbers are maximum 9 digits long